const PAPORI_PRODUCTS = [
  { name: "HIKMICRO MINIE", model: "MINIE", category: "열화상카메라 · 휴대용", price: null },
  { name: "HIKMICRO MINI-X", model: "MINI-X", category: "열화상카메라 · 휴대용", price: 540000 },
  { name: "HIKMICRO MINI2Plus V2", model: "MINI2Plus V2", category: "열화상카메라 · 휴대용", price: 350000 },
  { name: "HIKMICRO MINI2 V2", model: "MINI2 V2", category: "열화상카메라 · 휴대용", price: 300000 },
  { name: "HIKMICRO ECO Lite", model: "ECO Lite", category: "열화상카메라 · 휴대용", price: null },
  { name: "HIKMICRO ECO-V", model: "ECO-V", category: "열화상카메라 · 휴대용", price: 380000 },
  { name: "HIKMICRO B11S", model: "B11S", category: "열화상카메라 · 휴대용", price: 581818 },
  { name: "HIKMICRO B20S", model: "B20S", category: "열화상카메라 · 휴대용", price: 900000 },
  { name: "HIKMICRO POCKET2", model: "POCKET2", category: "열화상카메라 · 휴대용", price: 770000 },
  { name: "HIKMICRO M31T (열화상)", model: "M31T (열화상)", category: "열화상카메라 · 산업용", price: 4710000 },
  { name: "HIKMICRO M31", model: "M31", category: "열화상카메라 · 산업용", price: 3660000 },
  { name: "HIKMICRO M60", model: "M60", category: "열화상카메라 · 산업용", price: 6430000 },
  { name: "HIKMICRO M20W", model: "M20W", category: "열화상카메라 · 산업용", price: 2290000 },
  { name: "HIKMICRO M20", model: "M20", category: "열화상카메라 · 산업용", price: 2510000 },
  { name: "HIKMICRO M11W", model: "M11W", category: "열화상카메라 · 산업용", price: 1400000 },
  { name: "HIKMICRO M11", model: "M11", category: "열화상카메라 · 산업용", price: 1700000 },
  { name: "HIKMICRO G61H", model: "G61H", category: "열화상카메라 · 초고해상도", price: 17530000 },
  { name: "HIKMICRO G61", model: "G61", category: "열화상카메라 · 초고해상도", price: 16000000 },
  { name: "HIKMICRO G41H", model: "G41H", category: "열화상카메라 · 초고해상도", price: 16000000 },
  { name: "HIKMICRO G41", model: "G41", category: "열화상카메라 · 초고해상도", price: 11790000 },
  { name: "HIKMICRO G31", model: "G31", category: "열화상카메라 · 초고해상도", price: 7460000 },
  { name: "HIKMICRO SP120H", model: "SP120H", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO SP100H", model: "SP100H", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO SP60H", model: "SP60H", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO SP60", model: "SP60", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO SP40H", model: "SP40H", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO SP40", model: "SP40", category: "열화상카메라 · 초광각", price: null },
  { name: "HIKMICRO E02", model: "E02", category: "열화상카메라 · 휴대용", price: 285000 },
  { name: "HIKMICRO E01", model: "E01", category: "열화상카메라 · 휴대용", price: 255000 },
  { name: "HIKMICRO FB21", model: "FB21", category: "열화상카메라 · 소방용", price: 1400000 },
  { name: "HIKMICRO FT31", model: "FT31", category: "열화상카메라 · 소방용", price: 6000000 },
  { name: "HIKMICRO FP31", model: "FP31", category: "열화상카메라 · 소방용", price: 3000000 },
  { name: "HIKMICRO FP21", model: "FP21", category: "열화상카메라 · 소방용", price: 2000000 },
  { name: "HIKMICRO HM-TD3028T-3/Q", model: "HM-TD3028T-3/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD3028T-2/Q", model: "HM-TD3028T-2/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A67H1-25/Q", model: "HM-TD2A67H1-25/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A67H1-15/Q", model: "HM-TD2A67H1-15/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A67H2-7/Q", model: "HM-TD2A67H2-7/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO QF610", model: "QF610", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO QF310", model: "QF310", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A67T-25/Q", model: "HM-TD2A67T-25/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A67T-15/Q", model: "HM-TD2A67T-15/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A37T-25/Q", model: "HM-TD2A37T-25/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2A37T-15/Q", model: "HM-TD2A37T-15/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO HM-TD2C68E-25/Q", model: "HM-TD2C68E-25/Q", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO QD1210", model: "QD1210", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO QD610", model: "QD610", category: "열화상카메라 · 박스카메라", price: null },
  { name: "HIKMICRO Compact Microscopic System", model: "Compact Microscopic System", category: "열화상카메라 · 특수", price: null },
  { name: "HIKMICRO AI56 음향카메라", model: "AI56", category: "열화상카메라 · 음향카메라", price: 13950000 },
  { name: "HIKMICRO AI76 음향카메라", model: "AI76", category: "열화상카메라 · 음향카메라", price: 21400000 },
  { name: "HIKMICRO AI56L 음향카메라(다크비전)", model: "AI56L", category: "열화상카메라 · 음향카메라", price: null },
  { name: "초음파 활선 진단기 (디스콘스위치 점검용)", model: "US-DS100", category: "계측기", price: 1650000 },
  { name: "디지털 클램프미터 (교류/직류 전류측정기)", model: "CM-330", category: "계측기", price: 245000 },
  { name: "절연안전모 YSH-300 절연모", model: "YSH-300", category: "안전 장구류", price: 29700 },
  { name: "손목형 활선접근경보기 TK-802", model: "TK-802", category: "고압 활선작업 장구류", price: 68750 },
  { name: "오메가 절연장갑 저압용 1000V 천연고무", model: "저압용 1000V", category: "안전 장구류", price: 42900 },
  { name: "절연커버", model: "세원산업(SWIC)", category: "전기공사 기자재", price: null },
  { name: "내후성 케이블타이 (옥외용)", model: "HT-CT100", category: "헬러만타이톤", price: 38000 },
  { name: "마킹시스템 라벨프린터용 케이블 마커", model: "HT-MK200", category: "헬러만타이톤", price: null }
];
