// PAPORI 전체 상품 목록 (자동 생성 — product-detail-*.html에서 추출)
// 견적요청 페이지 자동완성 검색에 사용됩니다. 상품 페이지를 추가/수정한 뒤에는 이 파일도 재생성해야 합니다.
var PAPORI_PRODUCTS = [
  { id: "product-detail-ai56", name: "HIKMICRO AI56 음향카메라 (초음파 부분방전 진단)", model: "64채널 MEMS 마이크", category: "열화상카메라 · HIKMICRO", price: 13950000, url: "product-detail-ai56.html" },
  { id: "product-detail-ai56l", name: "HIKMICRO AI56L 음향카메라 (다크비전)", model: "AI56 기반 다크비전(저조도) 모델", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-ai56l.html" },
  { id: "product-detail-ai76", name: "HIKMICRO AI76 음향카메라 (초음파 부분방전 진단)", model: "136채널 마이크", category: "열화상카메라 · HIKMICRO", price: 21400000, url: "product-detail-ai76.html" },
  { id: "product-detail-b11s", name: "HIKMICRO B11S", model: "B11S", category: "열화상카메라 · HIKMICRO", price: 640000, url: "product-detail-b11s.html" },
  { id: "product-detail-b20s", name: "HIKMICRO B20S", model: "B20S", category: "열화상카메라 · HIKMICRO", price: 990000, url: "product-detail-b20s.html" },
  { id: "product-detail-chongwoo-bird-nest-cover", name: "조류둥지 방지커버", model: "특허 제10-1025700호", category: "한전 보수용 자재 · 청우테크", price: null, url: "product-detail-chongwoo-bird-nest-cover.html" },
  { id: "product-detail-chongwoo-connection-protector", name: "통신케이블 접속점 보호관", model: "大 / 小", category: "한전 보수용 자재 · 청우테크", price: null, url: "product-detail-chongwoo-connection-protector.html" },
  { id: "product-detail-chongwoo-hole-tent", name: "COS완금 및 홀완금 텐트 (까치집 방지)", model: "CW45TA", category: "한전 보수용 자재 · 청우테크", price: null, url: "product-detail-chongwoo-hole-tent.html" },
  { id: "product-detail-chongwoo-snake-cover", name: "SNAKE COVER (뱀커버)", model: "450mm x 900mm", category: "한전 보수용 자재 · 청우테크", price: null, url: "product-detail-chongwoo-snake-cover.html" },
  { id: "product-detail-e01", name: "HIKMICRO E01", model: "96×96", category: "열화상카메라 · HIKMICRO", price: 280500, url: "product-detail-e01.html" },
  { id: "product-detail-e02", name: "HIKMICRO E02", model: "96×96", category: "열화상카메라 · HIKMICRO", price: 313500, url: "product-detail-e02.html" },
  { id: "product-detail-eco-lite", name: "HIKMICRO ECO Lite", model: "ECO Lite", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-eco-lite.html" },
  { id: "product-detail-eco-v", name: "HIKMICRO ECO-V", model: "ECO-V", category: "열화상카메라 · HIKMICRO", price: 418000, url: "product-detail-eco-v.html" },
  { id: "product-detail-fb21", name: "HIKMICRO FB21", model: "FB21", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-fb21.html" },
  { id: "product-detail-fp21", name: "HIKMICRO FP21", model: "256×192", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-fp21.html" },
  { id: "product-detail-fp31", name: "HIKMICRO FP31", model: "FP31", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-fp31.html" },
  { id: "product-detail-ft31", name: "HIKMICRO FT31", model: "FT31", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-ft31.html" },
  { id: "product-detail-g31", name: "HIKMICRO G31 초고해상도 열화상카메라", model: "G31", category: "열화상카메라 · HIKMICRO", price: 8206000, url: "product-detail-g31.html" },
  { id: "product-detail-g41", name: "HIKMICRO G41 초고해상도 열화상카메라", model: "G41", category: "열화상카메라 · HIKMICRO", price: 12969000, url: "product-detail-g41.html" },
  { id: "product-detail-g41h", name: "HIKMICRO G41H 초고해상도 열화상카메라", model: "G41H", category: "열화상카메라 · HIKMICRO", price: 17600000, url: "product-detail-g41h.html" },
  { id: "product-detail-g61", name: "HIKMICRO G61 초고해상도 열화상카메라", model: "G61", category: "열화상카메라 · HIKMICRO", price: 17600000, url: "product-detail-g61.html" },
  { id: "product-detail-g61h", name: "HIKMICRO G61H 초고해상도 열화상카메라", model: "G61H", category: "열화상카메라 · HIKMICRO", price: 19283000, url: "product-detail-g61h.html" },
  { id: "product-detail-gana-20001", name: "다기능전압기록계(삼상) TYPE-2030", model: "모델 TYPE-2030", category: "계측기 · EDITECH", price: null, url: "product-detail-gana-20001.html" },
  { id: "product-detail-gana-20003", name: "다기능전압기록계(단상) TYPE-2010A", model: "모델 TYPE-2010A", category: "계측기 · EDITECH", price: null, url: "product-detail-gana-20003.html" },
  { id: "product-detail-gana-20004", name: "다기능전압기록계 TES-3600N", model: "모델 TES-3600N", category: "계측기 · TES", price: null, url: "product-detail-gana-20004.html" },
  { id: "product-detail-gana-20005", name: "3채널 전류·전압 로거 KEW 5020", model: "모델 KEW 5020", category: "계측기 · KYORITSU", price: null, url: "product-detail-gana-20005.html" },
  { id: "product-detail-gana-20006", name: "대구경 클램프미터 KEW 2002PA", model: "모델 KEW 2002PA", category: "계측기 · KYORITSU", price: 291500, url: "product-detail-gana-20006.html" },
  { id: "product-detail-gana-20007", name: "훅크온메다 TK-2000AD", model: "모델 TK-2000AD", category: "계측기 · TK (태광전자정밀)", price: 158400, url: "product-detail-gana-20007.html" },
  { id: "product-detail-gana-20008", name: "접지저항측정기 EST-9090", model: "모델 EST-9090", category: "계측기 · DADA", price: null, url: "product-detail-gana-20008.html" },
  { id: "product-detail-gana-20009", name: "클램프 접지저항계 KEW 4200", model: "모델 KEW 4200", category: "계측기 · KYORITSU", price: 1375000, url: "product-detail-gana-20009.html" },
  { id: "product-detail-gana-20010", name: "접지저항측정기 PROVA5601", model: "모델 PROVA5601", category: "계측기 · PROVA", price: null, url: "product-detail-gana-20010.html" },
  { id: "product-detail-gana-20011", name: "클램프접지저항계 TK-2060", model: "모델 TK-2060", category: "계측기 · TK (태광전자정밀)", price: 528000, url: "product-detail-gana-20011.html" },
  { id: "product-detail-gana-20013", name: "절연저항측정기 2804IN", model: "모델 2804IN", category: "계측기 · SEW", price: null, url: "product-detail-gana-20013.html" },
  { id: "product-detail-gana-20014", name: "절연저항측정기 DA-7410", model: "모델 DA-7410", category: "계측기 · DADA", price: 770000, url: "product-detail-gana-20014.html" },
  { id: "product-detail-gana-20017", name: "용량성검전기 TAG-200", model: "모델 TAG-200", category: "계측기 · HDE", price: null, url: "product-detail-gana-20017.html" },
  { id: "product-detail-gana-20018", name: "활선접근경보기 YS-212", model: "모델 YS-212", category: "계측기 · 유신기업사", price: 50930, url: "product-detail-gana-20018.html" },
  { id: "product-detail-gana-20019", name: "활선접근경보기 DA-3507", model: "모델 DA-3507", category: "계측기 · DADA", price: 99000, url: "product-detail-gana-20019.html" },
  { id: "product-detail-gana-20020", name: "활선접근경보기 DA-3505", model: "모델 DA-3505", category: "계측기 · DADA", price: null, url: "product-detail-gana-20020.html" },
  { id: "product-detail-gana-20021", name: "활선경보기 TK-808A", model: "모델 TK-808A", category: "계측기 · TK (태광전자정밀)", price: 14520, url: "product-detail-gana-20021.html" },
  { id: "product-detail-gana-20022", name: "활선접근경보기 QREI-D", model: "모델 QREI-D", category: "계측기 · 큐로", price: null, url: "product-detail-gana-20022.html" },
  { id: "product-detail-gana-20024", name: "다전압검전기 TK-300V", model: "모델 TK-300V", category: "계측기 · TK (태광전자정밀)", price: 132000, url: "product-detail-gana-20024.html" },
  { id: "product-detail-gana-20025", name: "특고압검전기 TK-1500V", model: "모델 TK-1500V", category: "계측기 · TK (태광전자정밀)", price: null, url: "product-detail-gana-20025.html" },
  { id: "product-detail-gana-20026", name: "무선검상기 TAG-5000", model: "모델 TAG-5000", category: "계측기 · FAMECA", price: 2530000, url: "product-detail-gana-20026.html" },
  { id: "product-detail-gana-20027", name: "154㎸ 검전기(YSD 100)", model: "모델 YSD 100", category: "계측기 · 유신기업사", price: 930000, url: "product-detail-gana-20027.html" },
  { id: "product-detail-gana-20028", name: "345㎸ 검전기(YSD 200)", model: "특고압HV", category: "계측기 · 유신기업사", price: 1165000, url: "product-detail-gana-20028.html" },
  { id: "product-detail-gana-20030", name: "절연저항측정기 TKM-920", model: "모델 TKM-920", category: "계측기 · TK (태광전자정밀)", price: 33000, url: "product-detail-gana-20030.html" },
  { id: "product-detail-gana-20031", name: "절연저항측정기 TKM-910", model: "모델 TKM-910", category: "계측기 · TK (태광전자정밀)", price: 33000, url: "product-detail-gana-20031.html" },
  { id: "product-detail-gana-20032", name: "AC 클램프미터 3280-10F", model: "모델 3280-10F", category: "계측기 · HIOKI", price: 86900, url: "product-detail-gana-20032.html" },
  { id: "product-detail-gana-20033", name: "슬림형 클램프미터 KEW 2200", model: "모델 KEW 2200", category: "계측기 · KYORITSU", price: 77000, url: "product-detail-gana-20033.html" },
  { id: "product-detail-gana-20034", name: "검상기 TK-107", model: "모델 TK-107", category: "계측기 · TK (태광전자정밀)", price: 39600, url: "product-detail-gana-20034.html" },
  { id: "product-detail-gana-20035", name: "저압검전기 HTE-610", model: "모델 HTE-610A", category: "계측기 · HASEGAWA", price: null, url: "product-detail-gana-20035.html" },
  { id: "product-detail-gana-20037", name: "카드형 하이테스터 3244-60", model: "모델 3244-60", category: "계측기 · HIOKI", price: 44000, url: "product-detail-gana-20037.html" },
  { id: "product-detail-gana-20038", name: "멀티미터 FLUKE #87-5", model: "모델 #87-5", category: "계측기 · FLUKE", price: null, url: "product-detail-gana-20038.html" },
  { id: "product-detail-gana-20040", name: "누설전류계 PROVA-11 PRO", model: "모델 PROVA-11 PRO", category: "계측기 · PROVA", price: 459800, url: "product-detail-gana-20040.html" },
  { id: "product-detail-gana-20041", name: "누설전류계 CEM DT-9809", model: "모델 DT-9809", category: "계측기 · CEM", price: null, url: "product-detail-gana-20041.html" },
  { id: "product-detail-gana-20042", name: "특고압전류계", model: "일반", category: "계측기 · 일반", price: null, url: "product-detail-gana-20042.html" },
  { id: "product-detail-gana-20043", name: "가스탐지기 MINIMAX X4", model: "모델 MINIMAX X4", category: "계측기 · HONEYWELL", price: null, url: "product-detail-gana-20043.html" },
  { id: "product-detail-gana-20044", name: "가스탐지기(산소농도측정기) MINIMAX RXT", model: "모델 MINIMAX RXT", category: "계측기 · HONEYWELL", price: null, url: "product-detail-gana-20044.html" },
  { id: "product-detail-gana-20045", name: "적외선 온도측정기", model: "모델 BO-350", category: "계측기 · 블루텍", price: null, url: "product-detail-gana-20045.html" },
  { id: "product-detail-gana-20046", name: "매설물탐지기 RD312", model: "모델 RD312", category: "계측기 · Radiodetection", price: null, url: "product-detail-gana-20046.html" },
  { id: "product-detail-gana-20047", name: "일제 스마트스틱 세트", model: "간접활선 작업용 공구", category: "간접활선공구 · NAGAKI", price: null, url: "product-detail-gana-20047.html" },
  { id: "product-detail-gana-20048", name: "국산 스마트스틱 세트", model: "간접활선 작업용 공구", category: "간접활선공구 · C&amp;C TOOL", price: null, url: "product-detail-gana-20048.html" },
  { id: "product-detail-gana-20049", name: "간접활선 방호구 및 시트클립", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 기자재", price: null, url: "product-detail-gana-20049.html" },
  { id: "product-detail-gana-20050", name: "유니버셜어댑터 (핫스틱용)", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20050.html" },
  { id: "product-detail-gana-20051", name: "브러쉬", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20051.html" },
  { id: "product-detail-gana-20052", name: "유니버셜 나이프(대)", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20052.html" },
  { id: "product-detail-gana-20053", name: "나이프 (대)", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20053.html" },
  { id: "product-detail-gana-20054", name: "간접활선용 옆가위 카타", model: "간접활선 작업용 공구", category: "간접활선공구 · Toolschamp", price: null, url: "product-detail-gana-20054.html" },
  { id: "product-detail-gana-20055", name: "간접활선 절단기", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20055.html" },
  { id: "product-detail-gana-20056", name: "점퍼선 홀딩스틱 A형,B형,C형", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20056.html" },
  { id: "product-detail-gana-20057", name: "활선용 완철", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20057.html" },
  { id: "product-detail-gana-20058", name: "스마트스틱 거치대", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20058.html" },
  { id: "product-detail-gana-20059", name: "간접활선 승압기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20059.html" },
  { id: "product-detail-gana-20060", name: "복스 + 바인드카타 (단종)", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20060.html" },
  { id: "product-detail-gana-20061", name: "홀더 일체형 유압 압축기", model: "간접활선 작업용 공구", category: "간접활선공구 · 케스코물산", price: null, url: "product-detail-gana-20061.html" },
  { id: "product-detail-gana-20062", name: "디지털 압축력 측정기", model: "간접활선 작업용 공구", category: "간접활선공구 · 케스코물산", price: null, url: "product-detail-gana-20062.html" },
  { id: "product-detail-gana-20063", name: "전선인장 슬리브 전용 다이스", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20063.html" },
  { id: "product-detail-gana-20064", name: "임시절연 단말캡 A형,B형", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20064.html" },
  { id: "product-detail-gana-20065", name: "로터스틱 어댑터", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20065.html" },
  { id: "product-detail-gana-20066", name: "로터스틱 부착형 전동공구", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20066.html" },
  { id: "product-detail-gana-20067", name: "스마트홀더", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20067.html" },
  { id: "product-detail-gana-20068", name: "간접활선 위험표지판 취부기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20068.html" },
  { id: "product-detail-gana-20069", name: "[NEW] 전선 종단 피박기", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20069.html" },
  { id: "product-detail-gana-20070", name: "임시걸이 일체형 클램프", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20070.html" },
  { id: "product-detail-gana-20071", name: "간접용 인성쇄클", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20071.html" },
  { id: "product-detail-gana-20072", name: "간접활선용 다기능활선 피박기", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20072.html" },
  { id: "product-detail-gana-20073", name: "간접활선용 테이핑기", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20073.html" },
  { id: "product-detail-gana-20074", name: "피박기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20074.html" },
  { id: "product-detail-gana-20075", name: "테이핑기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20075.html" },
  { id: "product-detail-gana-20076", name: "후크", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20076.html" },
  { id: "product-detail-gana-20077", name: "D형 후크", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20077.html" },
  { id: "product-detail-gana-20078", name: "나이프(대)", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20078.html" },
  { id: "product-detail-gana-20079", name: "바인드 커터 &amp; 복스 (단종)", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20079.html" },
  { id: "product-detail-gana-20080", name: "브러쉬", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20080.html" },
  { id: "product-detail-gana-20081", name: "유니버셜 어댑터(핫스틱용)", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20081.html" },
  { id: "product-detail-gana-20082", name: "라쳇렌치", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20082.html" },
  { id: "product-detail-gana-20083", name: "스패너", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20083.html" },
  { id: "product-detail-gana-20084", name: "애자포크", model: "간접활선 작업용 공구", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20084.html" },
  { id: "product-detail-gana-20085", name: "쐐기형 클램프 개방기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20085.html" },
  { id: "product-detail-gana-20086", name: "코터핀 교체공구", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20086.html" },
  { id: "product-detail-gana-20087", name: "간접활선용 임시절연 단말캡", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20087.html" },
  { id: "product-detail-gana-20088", name: "회전공구(확장형)", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20088.html" },
  { id: "product-detail-gana-20089", name: "바인드 제거기", model: "간접활선 작업용 공구", category: "간접활선공구 · 간접활선 작업용 공구", price: null, url: "product-detail-gana-20089.html" },
  { id: "product-detail-gana-20090", name: "사활선 감지기 CHS-1000", model: "모델 사활선 감지기 CHS-1000", category: "간접활선공구 · ToolsChamp", price: null, url: "product-detail-gana-20090.html" },
  { id: "product-detail-gana-20091", name: "OW 원통피박기 셋트", model: "간접활선 작업용 공구", category: "간접활선공구 · 국산", price: null, url: "product-detail-gana-20091.html" },
  { id: "product-detail-gana-20092", name: "접지용구 배전용", model: "활선 및 안전장구", category: "안전장구 · 활선 및 안전장구", price: null, url: "product-detail-gana-20092.html" },
  { id: "product-detail-gana-20093", name: "검측봉 9단 11m", model: "모델 YS-307", category: "안전장구 · 유신기업사", price: null, url: "product-detail-gana-20093.html" },
  { id: "product-detail-gana-20094", name: "절연안전모 ABE형", model: "모델 YSH-300", category: "안전장구 · 유신기업사", price: null, url: "product-detail-gana-20094.html" },
  { id: "product-detail-gana-20095", name: "방염마스크", model: "활선 및 안전장구", category: "안전장구 · 국산", price: null, url: "product-detail-gana-20095.html" },
  { id: "product-detail-gana-20096", name: "절연안전모 경보기내장형", model: "모델 YSH-100", category: "안전장구 · 유신기업사", price: null, url: "product-detail-gana-20096.html" },
  { id: "product-detail-gana-20097", name: "절연스틱작업용 건축용 COS덮개", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20097.html" },
  { id: "product-detail-gana-20098", name: "절연스틱 건축용 애자 덮개", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20098.html" },
  { id: "product-detail-gana-20099", name: "절연스틱 건축용 데드엔드커버", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20099.html" },
  { id: "product-detail-gana-20100", name: "절연스틱 건축용 분기방호구", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20100.html" },
  { id: "product-detail-gana-20101", name: "절연스틱 건축용 애자 덮개", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20101.html" },
  { id: "product-detail-gana-20102", name: "절연스틱 건축용 부싱덮개", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20102.html" },
  { id: "product-detail-gana-20103", name: "전선커버(전선덮개) 미제", model: "모델 P406-0184", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20103.html" },
  { id: "product-detail-gana-20104", name: "애자카바(애자덮개) 미제", model: "모델 C406-0182L", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20104.html" },
  { id: "product-detail-gana-20105", name: "완금카바(완금덮개) 미제", model: "모델 C406-0504", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20105.html" },
  { id: "product-detail-gana-20106", name: "COS카바(COS덮개) 미제", model: "모델 C406-0009", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20106.html" },
  { id: "product-detail-gana-20107", name: "임시COS Only 미제", model: "모델 PSC601-0346", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20107.html" },
  { id: "product-detail-gana-20108", name: "다목적 데드엔드카바 미제", model: "모델 C406-0537", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20108.html" },
  { id: "product-detail-gana-20109", name: "데드엔드카바 국산", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20109.html" },
  { id: "product-detail-gana-20110", name: "전주카바(전주덮개)미제", model: "모델 C406-0000", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20110.html" },
  { id: "product-detail-gana-20111", name: "라인호스 덮개형 미제", model: "모델 C406-0308", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20111.html" },
  { id: "product-detail-gana-20112", name: "라인호스 일반형 미제", model: "모델 C400-0342", category: "안전장구 · CHANCE", price: null, url: "product-detail-gana-20112.html" },
  { id: "product-detail-gana-20113", name: "고무브랑켓트 평형 미제", model: "모델 VB4-3636", category: "안전장구 · Saf-T-Gard", price: null, url: "product-detail-gana-20113.html" },
  { id: "product-detail-gana-20114", name: "고무브랑켓트 공형 미제", model: "모델 VB4-3636S", category: "안전장구 · Saf-T-Gard", price: null, url: "product-detail-gana-20114.html" },
  { id: "product-detail-gana-20115", name: "고압 고무소매 (직선형)", model: "모델 고압 고무절연소매 STRAIGHT TYPE", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20115.html" },
  { id: "product-detail-gana-20116", name: "EVA 고압 절연블랭킷 (26.5kV)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20116.html" },
  { id: "product-detail-gana-20117", name: "고압 절연소매", model: "모델 TK-IS-30", category: "안전장구 · TK", price: null, url: "product-detail-gana-20117.html" },
  { id: "product-detail-gana-20118", name: "호이스트링크스틱", model: "활선 및 안전장구", category: "안전장구 · 국산", price: null, url: "product-detail-gana-20118.html" },
  { id: "product-detail-gana-20119", name: "Class 00 절연고무장갑 (500V)", model: "모델 CNOVAX-00", category: "안전장구 · NOVAX", price: 41800, url: "product-detail-gana-20119.html" },
  { id: "product-detail-gana-20120", name: "Class 0 절연고무장갑 (1000V)", model: "모델 CNOVAX-0", category: "안전장구 · NOVAX", price: 44000, url: "product-detail-gana-20120.html" },
  { id: "product-detail-gana-20121", name: "Class 3 절연고무장갑 (26.5kV)", model: "모델 CNOVAX-3", category: "안전장구 · NOVAX", price: 108500, url: "product-detail-gana-20121.html" },
  { id: "product-detail-gana-20122", name: "방전고무장갑 26.5kV 일제", model: "모델 YS-101", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20122.html" },
  { id: "product-detail-gana-20123", name: "가죽보호장갑 미제", model: "활선 및 안전장구", category: "안전장구 · VOLTGARD", price: null, url: "product-detail-gana-20123.html" },
  { id: "product-detail-gana-20124", name: "라쳇트전선커터", model: "활선 및 안전장구", category: "안전장구 · 활선 및 안전장구", price: null, url: "product-detail-gana-20124.html" },
  { id: "product-detail-gana-20125", name: "인성쇄클", model: "활선 및 안전장구", category: "안전장구 · 국산", price: null, url: "product-detail-gana-20125.html" },
  { id: "product-detail-gana-20126", name: "충전부 임시절연캡", model: "활선 및 안전장구", category: "안전장구 · 활선 및 안전장구", price: null, url: "product-detail-gana-20126.html" },
  { id: "product-detail-gana-20127", name: "실리콘위험표지판", model: "활선 및 안전장구", category: "안전장구 · 활선 및 안전장구", price: null, url: "product-detail-gana-20127.html" },
  { id: "product-detail-gana-20128", name: "클램프핀 직구, 곡구", model: "활선 및 안전장구", category: "안전장구 · 국산", price: 18150, url: "product-detail-gana-20128.html" },
  { id: "product-detail-gana-20129", name: "버킷 거치용 절연고리", model: "활선 및 안전장구", category: "안전장구 · ToolsChamp", price: null, url: "product-detail-gana-20129.html" },
  { id: "product-detail-gana-20130", name: "스마트스틱 그립서포터 (보조손잡이)", model: "활선 및 안전장구", category: "안전장구 · ToolsChamp", price: null, url: "product-detail-gana-20130.html" },
  { id: "product-detail-gana-20131", name: "시트클립(직구형)", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20131.html" },
  { id: "product-detail-gana-20132", name: "시트클립 (곡구B)", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20132.html" },
  { id: "product-detail-gana-20134", name: "시트클립 (곡구A형)", model: "활선 및 안전장구", category: "안전장구 · 간접활선 기자재", price: null, url: "product-detail-gana-20134.html" },
  { id: "product-detail-gana-20135", name: "EVA 고압 절연블랭킷 SOLID (직선형)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET SOLID", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20135.html" },
  { id: "product-detail-gana-20136", name: "EVA 고압 절연블랭킷 SLOTTED (절개형)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET SLOTTED", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20136.html" },
  { id: "product-detail-gana-20137", name: "EVA 고압 절연블랭킷 (일반형)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET", category: "안전장구 · YOTSUGI", price: null, url: "product-detail-gana-20137.html" },
  { id: "product-detail-gana-20138", name: "애자후드", model: "모델 OKRG", category: "안전장구 · 활선 및 안전장구", price: null, url: "product-detail-gana-20138.html" },
  { id: "product-detail-gana-20139", name: "건축용 방호관", model: "활선 및 안전장구", category: "안전장구 · 풍국", price: null, url: "product-detail-gana-20139.html" },
  { id: "product-detail-gana-20141", name: "점퍼선방호관", model: "모델 YSN-305", category: "안전장구 · 유신기업사", price: null, url: "product-detail-gana-20141.html" },
  { id: "product-detail-gana-20142", name: "방전고무장갑 1000V", model: "모델 E-011B", category: "안전장구 · Salisbury(미제)", price: null, url: "product-detail-gana-20142.html" },
  { id: "product-detail-gana-20143", name: "방전고무장갑 26.5kV 미제", model: "활선 및 안전장구", category: "안전장구 · Salisbury 미제", price: null, url: "product-detail-gana-20143.html" },
  { id: "product-detail-gana-20145", name: "바이패스점퍼지지대", model: "활선 및 안전장구", category: "안전장구 · 국산", price: null, url: "product-detail-gana-20145.html" },
  { id: "product-detail-gana-20146", name: "안전허리띠세트 국제", model: "모델 #0074", category: "안전장구 · 국제", price: null, url: "product-detail-gana-20146.html" },
  { id: "product-detail-gana-20149", name: "전체식 안전그네 K472_전주인력오름용", model: "모델 K472", category: "안전장구 · 스왈록", price: null, url: "product-detail-gana-20149.html" },
  { id: "product-detail-gana-20150", name: "전체식 안전그네 K536_전주인력오름용", model: "모델 K536", category: "안전장구 · 스왈록", price: null, url: "product-detail-gana-20150.html" },
  { id: "product-detail-gana-20151", name: "전체식 안전그네 T010_전주인력오름용", model: "모델 T010", category: "안전장구 · 스왈록", price: null, url: "product-detail-gana-20151.html" },
  { id: "product-detail-gana-20152", name: "전체식 안전그네 K051-32_전주인력오름용", model: "모델 K051-32", category: "안전장구 · 국제", price: 42900, url: "product-detail-gana-20152.html" },
  { id: "product-detail-gana-20153", name: "상체식 안전대(엑스반도)", model: "모델 DH-103AR1", category: "안전장구 · 국산", price: null, url: "product-detail-gana-20153.html" },
  { id: "product-detail-gana-20154", name: "전동식 압축기펌프", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-gana-20154.html" },
  { id: "product-detail-gana-20155", name: "지중 케이블절단기 신성 SS85C", model: "모델 SS85C", category: "유압공구 · 신성", price: null, url: "product-detail-gana-20155.html" },
  { id: "product-detail-gana-20156", name: "지중 케이블절단기 오메가 HC-85B", model: "모델 HC-85B", category: "유압공구 · 오매가", price: null, url: "product-detail-gana-20156.html" },
  { id: "product-detail-gana-20157", name: "지중 유압압축기 이즈미 30톤", model: "모델 EP-520C", category: "유압공구 · 이즈미", price: null, url: "product-detail-gana-20157.html" },
  { id: "product-detail-gana-20158", name: "지중 유압압축기 가나 30톤", model: "모델 CCO-630B", category: "유압공구 · 가나", price: null, url: "product-detail-gana-20158.html" },
  { id: "product-detail-gana-20159", name: "유압압축기헤드 신성 GY-510H", model: "모델 GY-510H", category: "유압공구 · 신성", price: null, url: "product-detail-gana-20159.html" },
  { id: "product-detail-gana-20160", name: "유압압축기헤드 이즈미 EP-510HC", model: "모델 EP-510HC", category: "유압공구 · 이즈미", price: null, url: "product-detail-gana-20160.html" },
  { id: "product-detail-gana-20161", name: "유압 압축기헤드 신성 SS-410H", model: "모델 SS-410H", category: "유압공구 · 신성", price: null, url: "product-detail-gana-20161.html" },
  { id: "product-detail-gana-20162", name: "유압 압축기헤드 대림 DL-13H", model: "모델 DL-13H", category: "유압공구 · 대림전설", price: null, url: "product-detail-gana-20162.html" },
  { id: "product-detail-gana-20164", name: "전동식 압축기펌프 대진유압", model: "유압공구", category: "유압공구 · 대진유압", price: null, url: "product-detail-gana-20164.html" },
  { id: "product-detail-gana-20165", name: "유압카타 가위식 대림 DLC-2002", model: "모델 DLC-2002", category: "유압공구 · 대림전설", price: null, url: "product-detail-gana-20165.html" },
  { id: "product-detail-gana-20166", name: "유압 커터 (가위식)", model: "유압공구", category: "유압공구 · 가나", price: null, url: "product-detail-gana-20166.html" },
  { id: "product-detail-gana-20167", name: "간접활선용 유압 커터", model: "유압공구", category: "유압공구 · ToolsChamp", price: null, url: "product-detail-gana-20167.html" },
  { id: "product-detail-gana-20168", name: "충전식압축기 13톤 클라우케 EK12042CFM", model: "모델 EK12042-L", category: "유압공구 · Klauke", price: 3300000, url: "product-detail-gana-20168.html" },
  { id: "product-detail-gana-20169", name: "충전식 3in1 12톤 클라우케 EK120UNVL", model: "모델 EK120UNVL", category: "유압공구 · Klauke", price: null, url: "product-detail-gana-20169.html" },
  { id: "product-detail-gana-20170", name: "충전식 3in1 6톤 클라우케 EKM60UNVL", model: "모델 EKM60UNVL", category: "유압공구 · Klauke", price: null, url: "product-detail-gana-20170.html" },
  { id: "product-detail-gana-20171", name: "충전식압축기 6톤 클라우케 EK425L", model: "모델 EK425L", category: "유압공구 · Kaluke", price: null, url: "product-detail-gana-20171.html" },
  { id: "product-detail-gana-20172", name: "충전식압축기 6톤 클라우케 EKM6022L", model: "모델 EKM6022L", category: "유압공구 · Klauke", price: null, url: "product-detail-gana-20172.html" },
  { id: "product-detail-gana-20173", name: "충전식압축기 12톤 대진유압 TBCP400-40", model: "모델 TBCP400-40", category: "유압공구 · 대진유압", price: null, url: "product-detail-gana-20173.html" },
  { id: "product-detail-gana-20174", name: "압축력 시험기", model: "유압공구", category: "유압공구 · 이엘테크", price: null, url: "product-detail-gana-20174.html" },
  { id: "product-detail-gana-20175", name: "충전식 겸용 13톤 다이아 HPN-400RN", model: "모델 HPN-400RN", category: "유압공구 · DAIA", price: null, url: "product-detail-gana-20175.html" },
  { id: "product-detail-gana-20176", name: "압축기 다이스", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-gana-20176.html" },
  { id: "product-detail-gana-20178", name: "13톤 유압 케이블 압착기 18V,5.0A (배터리2,충전기1) 셋트", model: "모델 HCCT120ST-502C", category: "유압공구 · 밀워키", price: null, url: "product-detail-gana-20178.html" },
  { id: "product-detail-gana-20179", name: "수동식압축기 신성 SY-35", model: "모델 SY-35", category: "유압공구 · 신성", price: null, url: "product-detail-gana-20179.html" },
  { id: "product-detail-gana-20180", name: "수동식압축기 이즈미 EP-431", model: "모델 EP-431", category: "유압공구 · 이즈미", price: null, url: "product-detail-gana-20180.html" },
  { id: "product-detail-gana-20181", name: "다이스 세트", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-gana-20181.html" },
  { id: "product-detail-gana-20182", name: "중간압력게이지", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-gana-20182.html" },
  { id: "product-detail-gana-20183", name: "유압천공기 이즈미 SH-70B", model: "모델 SH-70B", category: "유압공구 · 이즈미", price: null, url: "product-detail-gana-20183.html" },
  { id: "product-detail-gana-20184", name: "간접활선용 유압식 커터 (옆가위식)", model: "유압공구", category: "유압공구 · ToolsChamp", price: null, url: "product-detail-gana-20184.html" },
  { id: "product-detail-gana-20188", name: "충전식 임팩렌치 디월트 DCF922P2", model: "모델 DCF922P2", category: "전동공구 · 디월트", price: 460000, url: "product-detail-gana-20188.html" },
  { id: "product-detail-gana-20190", name: "밀워키 임팩트렌치 II 1/2 인치 18V 5.0Ah", model: "모델 M18 FMTIW2F12", category: "전동공구 · 밀워키", price: 430000, url: "product-detail-gana-20190.html" },
  { id: "product-detail-gana-20195", name: "충전식 임팩렌치 마끼다 DTW300", model: "모델 DTW300", category: "전동공구 · 마끼다", price: 590000, url: "product-detail-gana-20195.html" },
  { id: "product-detail-gana-20199", name: "블록연선로라", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20199.html" },
  { id: "product-detail-gana-20200", name: "장선기 구찌/캄아롱", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20200.html" },
  { id: "product-detail-gana-20201", name: "활선 수동전선카타", model: "모델 CMCC24", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20201.html" },
  { id: "product-detail-gana-20202", name: "수동 볼트카타", model: "전설공구", category: "전설공구 · MCC", price: null, url: "product-detail-gana-20202.html" },
  { id: "product-detail-gana-20203", name: "활선용 장선기벨트", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20203.html" },
  { id: "product-detail-gana-20204", name: "케이블 풀링 다이", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20204.html" },
  { id: "product-detail-gana-20205", name: "수동식 휴즈압착기 이즈미 EH-1", model: "모델 EH-1", category: "전설공구 · IZUMI", price: null, url: "product-detail-gana-20205.html" },
  { id: "product-detail-gana-20206", name: "절연로라", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20206.html" },
  { id: "product-detail-gana-20207", name: "수동식 휴즈압착기 이즈미 EH-3N", model: "모델 EH-3N", category: "전설공구 · IZUMI", price: null, url: "product-detail-gana-20207.html" },
  { id: "product-detail-gana-20208", name: "수동식 휴즈압착기 이즈미 EH-2C", model: "모델 EH-2C", category: "전설공구 · IZUMI", price: null, url: "product-detail-gana-20208.html" },
  { id: "product-detail-gana-20209", name: "충전식 LED 버킷랜턴", model: "전설공구", category: "전설공구 · 밀워키", price: null, url: "product-detail-gana-20209.html" },
  { id: "product-detail-gana-20210", name: "활선피박기", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20210.html" },
  { id: "product-detail-gana-20211", name: "블록(연선로라)", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20211.html" },
  { id: "product-detail-gana-20212", name: "활선피박기 또는 다기능피박기", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20212.html" },
  { id: "product-detail-gana-20213", name: "클램프핀", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20213.html" },
  { id: "product-detail-gana-20214", name: "투광기", model: "모델 SL-747(S)", category: "전설공구 · 유니온라이트", price: null, url: "product-detail-gana-20214.html" },
  { id: "product-detail-gana-20215", name: "고휘도 조명장치", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20215.html" },
  { id: "product-detail-gana-20216", name: "고무장갑 백", model: "전설공구", category: "전설공구 · 가나상공", price: null, url: "product-detail-gana-20216.html" },
  { id: "product-detail-gana-20217", name: "고무소매 백", model: "전설공구", category: "전설공구 · 가나상공", price: null, url: "product-detail-gana-20217.html" },
  { id: "product-detail-gana-20218", name: "활선장선기 세트 국산", model: "전설공구", category: "전설공구 · 국산", price: null, url: "product-detail-gana-20218.html" },
  { id: "product-detail-gana-20219", name: "활선장선기 세트 일제", model: "모델 N-3", category: "전설공구 · NGK", price: null, url: "product-detail-gana-20219.html" },
  { id: "product-detail-gana-20220", name: "사선장선기 세트 국산", model: "전설공구", category: "전설공구 · 전설공구", price: null, url: "product-detail-gana-20220.html" },
  { id: "product-detail-gana-20221", name: "고임목(볼트有) 3kg, 5kg", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20221.html" },
  { id: "product-detail-gana-20222", name: "공구박스 / 대", model: "일반공구", category: "일반공구 · KL", price: null, url: "product-detail-gana-20222.html" },
  { id: "product-detail-gana-20223", name: "공구박스 / 3단수납대", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20223.html" },
  { id: "product-detail-gana-20224", name: "공구박스 / 1단4구", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20224.html" },
  { id: "product-detail-gana-20225", name: "공구박스 / 3칸(1단3구)", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20225.html" },
  { id: "product-detail-gana-20226", name: "장선기용 수납함 / 대", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20226.html" },
  { id: "product-detail-gana-20227", name: "공구박스 / 5칸 (2단)", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20227.html" },
  { id: "product-detail-gana-20228", name: "공구박스 / 5칸 (소)", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20228.html" },
  { id: "product-detail-gana-20229", name: "무선 액션 에어간판", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20229.html" },
  { id: "product-detail-gana-20230", name: "무선 에어간판", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20230.html" },
  { id: "product-detail-gana-20231", name: "무전기(업무용)", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20231.html" },
  { id: "product-detail-gana-20232", name: "유압안전발판(잭베이스)", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20232.html" },
  { id: "product-detail-gana-20233", name: "음주측정기", model: "일반공구", category: "일반공구 · 쎈텍", price: null, url: "product-detail-gana-20233.html" },
  { id: "product-detail-gana-20234", name: "고임목 설치 제거기", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20234.html" },
  { id: "product-detail-gana-20235", name: "공구박스 / 2칸", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20235.html" },
  { id: "product-detail-gana-20236", name: "안전표시찰", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20236.html" },
  { id: "product-detail-gana-20237", name: "고임목 7.32kg (길이275x높이200x폭185)", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20237.html" },
  { id: "product-detail-gana-20238", name: "고임목 8.5kg (길이290x높이220x폭195)", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20238.html" },
  { id: "product-detail-gana-20239", name: "공구함", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20239.html" },
  { id: "product-detail-gana-20240", name: "조끼", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20240.html" },
  { id: "product-detail-gana-20241", name: "칼라콘", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20241.html" },
  { id: "product-detail-gana-20242", name: "신호봉", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20242.html" },
  { id: "product-detail-gana-20243", name: "사다리", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20243.html" },
  { id: "product-detail-gana-20244", name: "호루라기(안전모 부착형)", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20244.html" },
  { id: "product-detail-gana-20245", name: "공구박스 / 2단3구", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20245.html" },
  { id: "product-detail-gana-20246", name: "케이블피박기", model: "모델 DW-13", category: "지중공사 공구 · 대원금속", price: null, url: "product-detail-gana-20246.html" },
  { id: "product-detail-gana-20247", name: "케이블드럼받침대", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20247.html" },
  { id: "product-detail-gana-20248", name: "접지엘보", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20248.html" },
  { id: "product-detail-gana-20249", name: "검전핀", model: "모델 370TR", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20249.html" },
  { id: "product-detail-gana-20250", name: "플레이트컴팩터", model: "모델 JPC-80", category: "지중공사 공구 · 전일기계", price: null, url: "product-detail-gana-20250.html" },
  { id: "product-detail-gana-20251", name: "가스제거기", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20251.html" },
  { id: "product-detail-gana-20252", name: "지상변압기붓싱 절연캡", model: "모델 273DRG", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20252.html" },
  { id: "product-detail-gana-20253", name: "반도전층피박기", model: "지중공사 공구", category: "지중공사 공구 · 제일테크", price: null, url: "product-detail-gana-20253.html" },
  { id: "product-detail-gana-20254", name: "풀링아이 다굴절", model: "지중공사 공구", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20254.html" },
  { id: "product-detail-gana-20255", name: "케이블피박기 절연체용", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20255.html" },
  { id: "product-detail-gana-20256", name: "스패너렌치", model: "모델 600SW", category: "지중공사 공구 · 이엘테크", price: null, url: "product-detail-gana-20256.html" },
  { id: "product-detail-gana-20257", name: "토크렌치", model: "지중공사 공구", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20257.html" },
  { id: "product-detail-gana-20258", name: "풀링아이", model: "지중공사 공구", category: "지중공사 공구 · HARU", price: null, url: "product-detail-gana-20258.html" },
  { id: "product-detail-gana-20259", name: "관로선통대", model: "모델 10Φ *305M", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20259.html" },
  { id: "product-detail-gana-20260", name: "워킹 카운터", model: "지중공사 공구", category: "지중공사 공구 · 블루버드", price: null, url: "product-detail-gana-20260.html" },
  { id: "product-detail-gana-20261", name: "케이블 풀링그립", model: "지중공사 공구", category: "지중공사 공구 · 동우", price: null, url: "product-detail-gana-20261.html" },
  { id: "product-detail-gana-20262", name: "AL케이블 계단형피박기 KIT", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20262.html" },
  { id: "product-detail-gana-20263", name: "조작핀(단종)", model: "지중공사 공구", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20263.html" },
  { id: "product-detail-gana-20264", name: "구조용삼각대", model: "모델 NTTP300 / 수동윈치", category: "지중공사 공구 · SG", price: null, url: "product-detail-gana-20264.html" },
  { id: "product-detail-gana-20265", name: "양수기 /호스별도", model: "모델 SHE80X", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20265.html" },
  { id: "product-detail-gana-20266", name: "맨홀뚜껑개방기", model: "지중공사 공구", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20266.html" },
  { id: "product-detail-gana-20267", name: "지중기기조작봉", model: "모델 YS 311", category: "지중공사 공구 · 유신기업사", price: null, url: "product-detail-gana-20267.html" },
  { id: "product-detail-gana-20268", name: "절연붓싱", model: "모델 272SOP", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20268.html" },
  { id: "product-detail-gana-20269", name: "바닥로라(전선로라, 케이블로라)", model: "지중공사 공구", category: "지중공사 공구 · 지중공사 공구", price: null, url: "product-detail-gana-20269.html" },
  { id: "product-detail-gana-20270", name: "관로도통시험기", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20270.html" },
  { id: "product-detail-gana-20271", name: "장력계", model: "지중공사 공구", category: "지중공사 공구 · 국산", price: null, url: "product-detail-gana-20271.html" },
  { id: "product-detail-gana-20272", name: "토크렌치", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20272.html" },
  { id: "product-detail-gana-20273", name: "케이블피박기 절연체용", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20273.html" },
  { id: "product-detail-gana-20274", name: "풀링아이 다굴절", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20274.html" },
  { id: "product-detail-gana-20275", name: "가스제거기", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20275.html" },
  { id: "product-detail-gana-20276", name: "검전핀", model: "모델 370TR", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20276.html" },
  { id: "product-detail-gana-20277", name: "장력계", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20277.html" },
  { id: "product-detail-gana-20278", name: "관로도통시험기", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20278.html" },
  { id: "product-detail-gana-20279", name: "바닥로라(전선로라, 케이블로라)", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20279.html" },
  { id: "product-detail-gana-20280", name: "지중기기조작봉", model: "모델 YS 311", category: "일반공구 · 유신기업사", price: null, url: "product-detail-gana-20280.html" },
  { id: "product-detail-gana-20281", name: "맨홀뚜껑개방기", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20281.html" },
  { id: "product-detail-gana-20282", name: "스패너렌치", model: "모델 600SW", category: "일반공구 · 이엘테크", price: null, url: "product-detail-gana-20282.html" },
  { id: "product-detail-gana-20283", name: "케이블피박기", model: "모델 DW-13", category: "일반공구 · 대원금속", price: null, url: "product-detail-gana-20283.html" },
  { id: "product-detail-gana-20284", name: "반도전층피박기", model: "일반공구", category: "일반공구 · 제일테크", price: null, url: "product-detail-gana-20284.html" },
  { id: "product-detail-gana-20285", name: "케이블프로텍터", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20285.html" },
  { id: "product-detail-gana-20286", name: "케이블 인류클램프", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20286.html" },
  { id: "product-detail-gana-20287", name: "전주체부밴드", model: "일반공구", category: "일반공구 · 국산", price: null, url: "product-detail-gana-20287.html" },
  { id: "product-detail-gana-20288", name: "바이패스점퍼스틱 또는 바이패스점퍼케이블", model: "일반공구", category: "일반공구 · 일반공구", price: null, url: "product-detail-gana-20288.html" },
  { id: "product-detail-jeryong-1", name: "간접활선용 임시절연 단말캡", model: "한전표준구매규격 GS-5935-0053 (A/B Type)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-1.html" },
  { id: "product-detail-jeryong-10", name: "간접활선용 폴리머현수애자 절연보강커버", model: "GS-5970-0073 / 127808", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-10.html" },
  { id: "product-detail-jeryong-11", name: "간접활선용 연장형 인류클램프 절연커버", model: "한전표준구매규격 (240SQ이하 전 규격)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-11.html" },
  { id: "product-detail-jeryong-12", name: "간접활선용 부싱단자커버", model: "한전표준구매규격 (자기제", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-12.html" },
  { id: "product-detail-jeryong-13", name: "간접활선용 케이블헤드 절연커버", model: "한전 표준구매규격", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-13.html" },
  { id: "product-detail-jeryong-14", name: "알루미늄선용 분기슬리브", model: "ES-5935-0001", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-14.html" },
  { id: "product-detail-jeryong-2", name: "간접활선용 점퍼선슬리브세트 (Al선/Cu선)", model: "한전표준구매규격 (동종", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-2.html" },
  { id: "product-detail-jeryong-3", name: "간접활선용 임시걸이", model: "GS-5935-0055 / 126975", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-3.html" },
  { id: "product-detail-jeryong-4", name: "간접활선용 전선인장슬리브", model: "한전표준구매규격 (58/95/160SQ)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-4.html" },
  { id: "product-detail-jeryong-5", name: "간접활선용 분기슬리브 절연커버", model: "한전표준구매규격 (160SQ이하 / 240SQ전용)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-5.html" },
  { id: "product-detail-jeryong-6", name: "간접활선용 바인드레스 LP커버", model: "한전표준구매규격 (32/58/95/160/240SQ)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-6.html" },
  { id: "product-detail-jeryong-7", name: "간접활선용 분기고리 절연커버", model: "한전표준구매규격 (240SQ이하 전 규격)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-7.html" },
  { id: "product-detail-jeryong-8", name: "간접활선용 종단캡", model: "한전표준구매규격 (160SQ이하 전 규격)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-8.html" },
  { id: "product-detail-jeryong-9", name: "간접활선용 컴팩트절연보강커버", model: "한전표준구매규격 (240SQ이하 전규격)", category: "한전 보수용 자재 · 간접활선 기자재", price: null, url: "product-detail-jeryong-9.html" },
  { id: "product-detail-lantern-cf-3s", name: "폴라리온 CF-3S LED 연기투시랜턴", model: "모델 CF-3S", category: "랜턴 · POLARION", price: 330000, url: "product-detail-lantern-cf-3s.html" },
  { id: "product-detail-lantern-ps-np5", name: "폴라리온 PS-NP5 HID 라이트", model: "모델 PS-NP5", category: "랜턴 · POLARION", price: 1155000, url: "product-detail-lantern-ps-np5.html" },
  { id: "product-detail-lantern-ps-x1", name: "폴라리온 PS-X1 HID 제논탐조등", model: "모델 PS-X1", category: "랜턴 · POLARION", price: 1166000, url: "product-detail-lantern-ps-x1.html" },
  { id: "product-detail-lantern-sl-x", name: "폴라리온 SL-X LED 라이트", model: "모델 SL-X", category: "랜턴 · POLARION", price: 198000, url: "product-detail-lantern-sl-x.html" },
  { id: "product-detail-lantern-ssled-102", name: "유니비스 트윈라이트 SSLED-102", model: "모델 SSLED-102", category: "랜턴 · UNIVIS", price: null, url: "product-detail-lantern-ssled-102.html" },
  { id: "product-detail-lantern-uled-747d", name: "유니비스 서치라이트 ULED-747D", model: "모델 ULED-747D", category: "랜턴 · UNIVIS", price: null, url: "product-detail-lantern-uled-747d.html" },
  { id: "product-detail-m11", name: "HIKMICRO M11 전문가용 열화상카메라", model: "M11", category: "열화상카메라 · HIKMICRO", price: 1870000, url: "product-detail-m11.html" },
  { id: "product-detail-m11w", name: "HIKMICRO M11W", model: "M11W", category: "열화상카메라 · HIKMICRO", price: 1540000, url: "product-detail-m11w.html" },
  { id: "product-detail-m20", name: "HIKMICRO M20", model: "M20", category: "열화상카메라 · HIKMICRO", price: 2761000, url: "product-detail-m20.html" },
  { id: "product-detail-m20w", name: "HIKMICRO M20W 전문가용 열화상카메라", model: "M20W", category: "열화상카메라 · HIKMICRO", price: 2519000, url: "product-detail-m20w.html" },
  { id: "product-detail-m31", name: "HIKMICRO M31 전문가용 열화상카메라", model: "M31", category: "열화상카메라 · HIKMICRO", price: 4026000, url: "product-detail-m31.html" },
  { id: "product-detail-m31t", name: "HIKMICRO M31T (인체용) 초정밀 열화상카메라", model: "M31T(초정밀)", category: "열화상카메라 · HIKMICRO", price: 5181000, url: "product-detail-m31t.html" },
  { id: "product-detail-m60", name: "HIKMICRO M60", model: "M60", category: "열화상카메라 · HIKMICRO", price: 7073000, url: "product-detail-m60.html" },
  { id: "product-detail-marker", name: "마킹시스템 라벨프린터용 케이블 마커", model: "HT-MK200", category: " · HellermannTyton", price: null, url: "product-detail-marker.html" },
  { id: "product-detail-meter-cm4373-50", name: "AC/DC 클램프미터 CM4373-50", model: "모델 CM4373-50", category: "계측기 · HIOKI", price: 414700, url: "product-detail-meter-cm4373-50.html" },
  { id: "product-detail-meter-dt4252", name: "디지털 멀티미터 DT4252", model: "모델 DT4252", category: "계측기 · HIOKI", price: 156200, url: "product-detail-meter-dt4252.html" },
  { id: "product-detail-meter-fluke374fc", name: "AC/DC 클램프미터 FLUKE 374FC", model: "모델 374 FC", category: "계측기 · FLUKE", price: 511500, url: "product-detail-meter-fluke374fc.html" },
  { id: "product-detail-meter-hsn6a1", name: "고압 검전기 HSN-6A1", model: "모델 HSN-6A1", category: "계측기 · HASEGAWA", price: null, url: "product-detail-meter-hsn6a1.html" },
  { id: "product-detail-meter-hss25b1", name: "고압 검전기 HSS-25B1", model: "모델 HSS-25B1", category: "계측기 · HASEGAWA", price: null, url: "product-detail-meter-hss25b1.html" },
  { id: "product-detail-meter-hst15n", name: "AC/DC 겸용 고압 검전기 HST-1.5N", model: "모델 HST-1.5N", category: "계측기 · HASEGAWA", price: null, url: "product-detail-meter-hst15n.html" },
  { id: "product-detail-meter-hst170", name: "특고압 검전기 HST-170", model: "모델 HST-170", category: "계측기 · HASEGAWA", price: null, url: "product-detail-meter-hst170.html" },
  { id: "product-detail-meter-hst30w", name: "고압~특고압 검전기 HST-30W", model: "모델 HST-30W", category: "계측기 · HASEGAWA", price: null, url: "product-detail-meter-hst30w.html" },
  { id: "product-detail-meter-hxw6w", name: "손목시계형 활선접근경보기 HXW-6W", model: "모델 HXW-6W", category: "계측기 · HASEGAWA", price: 148500, url: "product-detail-meter-hxw6w.html" },
  { id: "product-detail-meter-kew8035", name: "비접촉검상기 KEW 8035", model: "모델 KEW 8035", category: "계측기 · KYORITSU", price: 234300, url: "product-detail-meter-kew8035.html" },
  { id: "product-detail-meter-pd3129", name: "검상기 PD3129", model: "모델 PD3129", category: "계측기 · HIOKI", price: 216700, url: "product-detail-meter-pd3129.html" },
  { id: "product-detail-mini2-v2", name: "HIKMICRO MINI2 V2", model: "MINI2 V2", category: "열화상카메라 · HIKMICRO", price: 330000, url: "product-detail-mini2-v2.html" },
  { id: "product-detail-mini2", name: "HIKMICRO MINI2 V2", model: "256×192", category: "열화상카메라 · HIKMICRO", price: 330000, url: "product-detail-mini2.html" },
  { id: "product-detail-mini2plus-v2", name: "HIKMICRO MINI2Plus V2", model: "MINI2Plus V2", category: "열화상카메라 · HIKMICRO", price: 385000, url: "product-detail-mini2plus-v2.html" },
  { id: "product-detail-mini2plus", name: "HIKMICRO MINI2Plus V2", model: "256×192", category: "열화상카메라 · HIKMICRO", price: 385000, url: "product-detail-mini2plus.html" },
  { id: "product-detail-minie", name: "HIKMICRO MiniE", model: "MiniE", category: "열화상카메라 · HIKMICRO", price: null, url: "product-detail-minie.html" },
  { id: "product-detail-minix", name: "HIKMICRO MINI-X", model: "MINI-X", category: "열화상카메라 · HIKMICRO", price: 594000, url: "product-detail-minix.html" },
  { id: "product-detail-pocket2", name: "HIKMICRO POCKET2 직무고시 열화상카메라", model: "POCKET2", category: "열화상카메라 · HIKMICRO", price: 770000, url: "product-detail-pocket2.html" },
  { id: "product-detail-sewon-1", name: "합성수지제 단독계기함 (기계식)", model: "품목번호 120927 / 120929", category: "한전 보수용 자재 · 세원산업", price: null, url: "product-detail-sewon-1.html" },
  { id: "product-detail-sewon-2", name: "합성수지제 단독계기함 (전자식)", model: "품목번호 120928 / 120930", category: "한전 보수용 자재 · 세원산업", price: null, url: "product-detail-sewon-2.html" },
  { id: "product-detail-sewon-3", name: "전선관용 부속품 (커넥터·커플링)", model: "호칭 16 / 22 / 28", category: "한전 보수용 자재 · 세원산업", price: null, url: "product-detail-sewon-3.html" },
  { id: "product-detail-sp100h", name: "HIKMICRO SP100H 초고성능 열화상카메라", model: "SP100H", category: "열화상카메라 · HIKMICRO", price: 53020000, url: "product-detail-sp100h.html" },
  { id: "product-detail-sp120h", name: "HIKMICRO SP120H 초고성능 열화상카메라", model: "SP120H", category: "열화상카메라 · HIKMICRO", price: 64790000, url: "product-detail-sp120h.html" },
  { id: "product-detail-sp40", name: "HIKMICRO SP40 초고성능 열화상카메라", model: "SP40", category: "열화상카메라 · HIKMICRO", price: 16830000, url: "product-detail-sp40.html" },
  { id: "product-detail-sp40h", name: "HIKMICRO SP40H 초고성능 열화상카메라", model: "SP40H", category: "열화상카메라 · HIKMICRO", price: 23320000, url: "product-detail-sp40h.html" },
  { id: "product-detail-sp60", name: "HIKMICRO SP60 초고성능 열화상카메라", model: "SP60", category: "열화상카메라 · HIKMICRO", price: 24200000, url: "product-detail-sp60.html" },
  { id: "product-detail-sp60h", name: "HIKMICRO SP60H 초고성능 열화상카메라", model: "SP60H", category: "열화상카메라 · HIKMICRO", price: 28820000, url: "product-detail-sp60h.html" },
  { id: "product-detail-sunsco-10", name: "ME3030B 전자파측정기", model: "계측기", category: "계측기 · 계측기", price: 319000, url: "product-detail-sunsco-10.html" },
  { id: "product-detail-sunsco-101", name: "칡넝쿨방지캡 표준형 1박스 (10EA) | 덩굴 식물 차단 보호캡", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 341000, url: "product-detail-sunsco-101.html" },
  { id: "product-detail-sunsco-102", name: "COS 퓨즈링크 | 과전류 보호 자재", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 42900, url: "product-detail-sunsco-102.html" },
  { id: "product-detail-sunsco-103", name: "실리콘위험표지판 (특고압용) 50개 | 특고압 위험 경고 표지판", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 907500, url: "product-detail-sunsco-103.html" },
  { id: "product-detail-sunsco-104", name: "실리콘위험표지판 (저압용) 50개 | 저압 위험 경고 표지판", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 742500, url: "product-detail-sunsco-104.html" },
  { id: "product-detail-sunsco-105", name: "건축용방호관 / 점퍼선방호관 (인증)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 14300, url: "product-detail-sunsco-105.html" },
  { id: "product-detail-sunsco-106", name: "친환경 전선퓨즈 3.2 (50A) | 과전류 차단 전선 보호용", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 319000, url: "product-detail-sunsco-106.html" },
  { id: "product-detail-sunsco-107", name: "ASS 커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-107.html" },
  { id: "product-detail-sunsco-108", name: "COS 커버 (상부)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-108.html" },
  { id: "product-detail-sunsco-109", name: "COS 커버 (하부)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-109.html" },
  { id: "product-detail-sunsco-11", name: "1393 / 1394S (3축) 전자파측정기", model: "계측기", category: "계측기 · 계측기", price: 437800, url: "product-detail-sunsco-11.html" },
  { id: "product-detail-sunsco-110", name: "바이오넷 퓨즈", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 39600, url: "product-detail-sunsco-110.html" },
  { id: "product-detail-sunsco-111", name: "부싱 단자 커버 (활선용) 1박스 (40EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 154000, url: "product-detail-sunsco-111.html" },
  { id: "product-detail-sunsco-112", name: "분기고리커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 3520, url: "product-detail-sunsco-112.html" },
  { id: "product-detail-sunsco-113", name: "분기슬리브커버 1박스 (50EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 104500, url: "product-detail-sunsco-113.html" },
  { id: "product-detail-sunsco-114", name: "인류클램프커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 4400, url: "product-detail-sunsco-114.html" },
  { id: "product-detail-sunsco-115", name: "이중절연자기 융착테이프 1박스 (100EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 363000, url: "product-detail-sunsco-115.html" },
  { id: "product-detail-sunsco-116", name: "활선근접경보기", model: "안전장구", category: "안전장구 · 안전장구", price: 55000, url: "product-detail-sunsco-116.html" },
  { id: "product-detail-sunsco-117", name: "COS 조작봉 YSC-300-3 | 전기 작업용 절연 조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 220000, url: "product-detail-sunsco-117.html" },
  { id: "product-detail-sunsco-118", name: "방진마스크", model: "안전장구", category: "안전장구 · 안전장구", price: 88000, url: "product-detail-sunsco-118.html" },
  { id: "product-detail-sunsco-119", name: "자급식호흡기구 (선양테크)", model: "안전장구", category: "안전장구 · 안전장구", price: 126500, url: "product-detail-sunsco-119.html" },
  { id: "product-detail-sunsco-120", name: "말벌보호복", model: "안전장구", category: "안전장구 · 안전장구", price: 539000, url: "product-detail-sunsco-120.html" },
  { id: "product-detail-sunsco-121", name: "방염복 추동복 추동계 (상의, 하의)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-121.html" },
  { id: "product-detail-sunsco-122", name: "절연안전화 ELECT 4인치", model: "안전장구", category: "안전장구 · 안전장구", price: 165000, url: "product-detail-sunsco-122.html" },
  { id: "product-detail-sunsco-123", name: "건설안전화 4, 6인치", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-123.html" },
  { id: "product-detail-sunsco-124", name: "COS 조작봉 YSC-300-4 | 전기 작업용 절연 조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 220000, url: "product-detail-sunsco-124.html" },
  { id: "product-detail-sunsco-125", name: "전선커버 (국산, 미제)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 143000, url: "product-detail-sunsco-125.html" },
  { id: "product-detail-sunsco-126", name: "[2월 생산 예정] 체결형 케이블 바인더 (800EA, 180EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 124190, url: "product-detail-sunsco-126.html" },
  { id: "product-detail-sunsco-127", name: "다목적데드엔드커버", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 170500, url: "product-detail-sunsco-127.html" },
  { id: "product-detail-sunsco-128", name: "EVA 고압 절연블랭킷 (일제 절연시트)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET", category: "간접활선공구 · YOTSUGI", price: null, url: "product-detail-sunsco-128.html" },
  { id: "product-detail-sunsco-129", name: "고무브랑켓트 (평형)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 242000, url: "product-detail-sunsco-129.html" },
  { id: "product-detail-sunsco-13", name: "Ior 로거 KEW 5050SE", model: "모델 KEW 5050SE", category: "계측기 · KYORITSU", price: null, url: "product-detail-sunsco-13.html" },
  { id: "product-detail-sunsco-130", name: "절연장화 (전기용 내전압 안전화)", model: "모델 Dielectric Insulating Boots", category: "간접활선공구 · 활선/절연", price: 220000, url: "product-detail-sunsco-130.html" },
  { id: "product-detail-sunsco-131", name: "절연매트 1000V", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 242000, url: "product-detail-sunsco-131.html" },
  { id: "product-detail-sunsco-132", name: "친환경 전선퓨즈 22 (100A) | 과전류 차단 전선 보호용", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 825000, url: "product-detail-sunsco-132.html" },
  { id: "product-detail-sunsco-133", name: "라쳇전선커터", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 1760000, url: "product-detail-sunsco-133.html" },
  { id: "product-detail-sunsco-134", name: "지중기기조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 649000, url: "product-detail-sunsco-134.html" },
  { id: "product-detail-sunsco-135", name: "방염복 동계 솜점퍼 솜바지 (상의, 하의)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-135.html" },
  { id: "product-detail-sunsco-136", name: "친환경 전선퓨즈 38 (150A) | 과전류 차단 전선 보호용", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 1430000, url: "product-detail-sunsco-136.html" },
  { id: "product-detail-sunsco-137", name: "COS 조작봉 YSC-300-5 | 전기 작업용 절연 조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 280500, url: "product-detail-sunsco-137.html" },
  { id: "product-detail-sunsco-14", name: "TESTO 510 온도계 습도계 차압계", model: "모델 510", category: "계측기 · TESTO", price: null, url: "product-detail-sunsco-14.html" },
  { id: "product-detail-sunsco-140", name: "친환경 전선퓨즈 60 (200A) | 과전류 차단 전선 보호용", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 1430000, url: "product-detail-sunsco-140.html" },
  { id: "product-detail-sunsco-141", name: "친환경 전선퓨즈 100 (300A) | 과전류 차단 전선 보호용", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 2200000, url: "product-detail-sunsco-141.html" },
  { id: "product-detail-sunsco-149", name: "fluke-62-max+ (적외선 온도계)", model: "모델 62 MAX+", category: "계측기 · FLUKE", price: null, url: "product-detail-sunsco-149.html" },
  { id: "product-detail-sunsco-152", name: "변압기테스터기 (다이아텍 / HD) HDE TILT II", model: "모델 HDE TILT II", category: "계측기 · 다이아텍(HD)", price: 990000, url: "product-detail-sunsco-152.html" },
  { id: "product-detail-sunsco-153", name: "접지저항계 FT6031-50", model: "모델 FT6031-50", category: "계측기 · HIOKI", price: 480000, url: "product-detail-sunsco-153.html" },
  { id: "product-detail-sunsco-154", name: "오픈코어 클램프 멀티미터 KEW MATE 2012RA", model: "모델 KEW MATE 2012RA", category: "계측기 · KYORITSU", price: 275000, url: "product-detail-sunsco-154.html" },
  { id: "product-detail-sunsco-155", name: "검상기 PD3129-10 (비접촉식)", model: "모델 PD3129-10", category: "계측기 · HIOKI", price: 275000, url: "product-detail-sunsco-155.html" },
  { id: "product-detail-sunsco-156", name: "미니 누설전류 클램프미터 M-140", model: "모델 M-140", category: "계측기 · MULTI", price: 308000, url: "product-detail-sunsco-156.html" },
  { id: "product-detail-sunsco-157", name: "정밀 누설전류계 KEW 2432", model: "모델 KEW 2432", category: "계측기 · KYORITSU", price: 550000, url: "product-detail-sunsco-157.html" },
  { id: "product-detail-sunsco-158", name: "피뢰기 열화진단 클램프테스터 ALCL-40L", model: "모델 ALCL-40L", category: "계측기 · MULTI", price: 3300000, url: "product-detail-sunsco-158.html" },
  { id: "product-detail-sunsco-161", name: "누전분석기", model: "계측기", category: "계측기 · 계측기", price: null, url: "product-detail-sunsco-161.html" },
  { id: "product-detail-sunsco-163", name: "특고압검상기 CATU", model: "계측기", category: "계측기 · CATU", price: null, url: "product-detail-sunsco-163.html" },
  { id: "product-detail-sunsco-169", name: "COS 조작봉 YSC-300-6 | 전기 작업용 절연 조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 280500, url: "product-detail-sunsco-169.html" },
  { id: "product-detail-sunsco-170", name: "FRP 유압체인톱 (그린리)", model: "유압공구", category: "유압공구 · 유압공구", price: 3025000, url: "product-detail-sunsco-170.html" },
  { id: "product-detail-sunsco-171", name: "다이스 (휴즈, 육각)", model: "유압공구", category: "유압공구 · 유압공구", price: 110000, url: "product-detail-sunsco-171.html" },
  { id: "product-detail-sunsco-172", name: "압축력시험기 (국산)", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-172.html" },
  { id: "product-detail-sunsco-187", name: "지선커버 (상, 하부) 1박스 (10EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 132000, url: "product-detail-sunsco-187.html" },
  { id: "product-detail-sunsco-188", name: "전선위험표지판", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-188.html" },
  { id: "product-detail-sunsco-189", name: "지중케이블보호판 1000*500*5T", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 16500, url: "product-detail-sunsco-189.html" },
  { id: "product-detail-sunsco-190", name: "풍차식조류방지기", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 19250, url: "product-detail-sunsco-190.html" },
  { id: "product-detail-sunsco-191", name: "피뢰기단자커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-191.html" },
  { id: "product-detail-sunsco-192", name: "PVC T형 애자 (규격품) 1박스 (50EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 121000, url: "product-detail-sunsco-192.html" },
  { id: "product-detail-sunsco-193", name: "인입용 앵글 (500, 1000, 1500mm) 1박스 (10EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 49500, url: "product-detail-sunsco-193.html" },
  { id: "product-detail-sunsco-194", name: "저압이질금속슬리브", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-194.html" },
  { id: "product-detail-sunsco-195", name: "분기슬리브 | 전선 배선 접속 자재", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 99000, url: "product-detail-sunsco-195.html" },
  { id: "product-detail-sunsco-196", name: "컷아웃스위치 (COS) 몸체, 홀더", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 44000, url: "product-detail-sunsco-196.html" },
  { id: "product-detail-sunsco-197", name: "전주도색판 (철판) 10개", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 198000, url: "product-detail-sunsco-197.html" },
  { id: "product-detail-sunsco-198", name: "스티커형 전주도색판 1박스 (100EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 2530000, url: "product-detail-sunsco-198.html" },
  { id: "product-detail-sunsco-199", name: "동바인드선", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-199.html" },
  { id: "product-detail-sunsco-200", name: "DV 전선 (1타=300M)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-200.html" },
  { id: "product-detail-sunsco-201", name: "지선이물방지커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 55000, url: "product-detail-sunsco-201.html" },
  { id: "product-detail-sunsco-208", name: "클램프 접지저항계 FT6380-50", model: "모델 FT6380-50", category: "계측기 · HIOKI", price: 1815000, url: "product-detail-sunsco-208.html" },
  { id: "product-detail-sunsco-25", name: "안전대 YS 88", model: "안전장구", category: "안전장구 · 안전장구", price: 192500, url: "product-detail-sunsco-25.html" },
  { id: "product-detail-sunsco-48", name: "안전지키미 (SU-9R)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-48.html" },
  { id: "product-detail-sunsco-49", name: "절연 안전모 YSH-300 | 전기작업용 산업 안전모", model: "안전장구", category: "안전장구 · 안전장구", price: 27500, url: "product-detail-sunsco-49.html" },
  { id: "product-detail-sunsco-50", name: "절연 안전모 YSH-100 | 경보기내장형 안전모", model: "안전장구", category: "안전장구 · 안전장구", price: 99000, url: "product-detail-sunsco-50.html" },
  { id: "product-detail-sunsco-509", name: "AC/DC 클램프미터 CM4375-50", model: "모델 CM4375-50", category: "계측기 · HIOKI", price: 504900, url: "product-detail-sunsco-509.html" },
  { id: "product-detail-sunsco-51", name: "안전조끼 2011XEE", model: "안전장구", category: "안전장구 · 안전장구", price: 44000, url: "product-detail-sunsco-51.html" },
  { id: "product-detail-sunsco-510", name: "디지털 멀티미터 DT4261", model: "모델 DT4261", category: "계측기 · HIOKI", price: 317900, url: "product-detail-sunsco-510.html" },
  { id: "product-detail-sunsco-511", name: "전원품질 아날라이저 PQ3100", model: "모델 PQ3100", category: "계측기 · HIOKI", price: null, url: "product-detail-sunsco-511.html" },
  { id: "product-detail-sunsco-512", name: "AC/DC 클램프미터 CM4375-91 (P2000 고전압 프로브 세트)", model: "모델 CM4375-91", category: "계측기 · HIOKI", price: 603900, url: "product-detail-sunsco-512.html" },
  { id: "product-detail-sunsco-513", name: "AC/DC 클램프미터 CM4373-91 (P2000 고전압 프로브 세트)", model: "모델 CM4373-91", category: "계측기 · HIOKI", price: null, url: "product-detail-sunsco-513.html" },
  { id: "product-detail-sunsco-514", name: "고전압 절연저항계 IR5051", model: "모델 IR5051", category: "계측기 · HIOKI", price: null, url: "product-detail-sunsco-514.html" },
  { id: "product-detail-sunsco-515", name: "디지털 멀티미터 DT4253", model: "모델 DT4253", category: "계측기 · HIOKI", price: 247500, url: "product-detail-sunsco-515.html" },
  { id: "product-detail-sunsco-516", name: "전원품질 아날라이저 PQ3100-91 (600A 센서 2개 세트)", model: "모델 PQ3100-91", category: "계측기 · HIOKI", price: null, url: "product-detail-sunsco-516.html" },
  { id: "product-detail-sunsco-517", name: "전원품질 아날라이저 PQ3100-92 (600A 센서 4개 세트)", model: "모델 PQ3100-92", category: "계측기 · HIOKI", price: null, url: "product-detail-sunsco-517.html" },
  { id: "product-detail-sunsco-519", name: "간접활선용 절연스틱", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-519.html" },
  { id: "product-detail-sunsco-52", name: "절연안전화 ELEG2 6인치", model: "안전장구", category: "안전장구 · 안전장구", price: 203500, url: "product-detail-sunsco-52.html" },
  { id: "product-detail-sunsco-523", name: "구조용삼각대(송풍기형)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-523.html" },
  { id: "product-detail-sunsco-524", name: "자동심장충격기(AED)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-524.html" },
  { id: "product-detail-sunsco-525", name: "송기마스크(2인용)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-525.html" },
  { id: "product-detail-sunsco-526", name: "공기호흡기(1시간용)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-526.html" },
  { id: "product-detail-sunsco-527", name: "절연스틱작업용 건축용 방호구 7종", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-527.html" },
  { id: "product-detail-sunsco-528", name: "EVA 고압 절연블랭킷 3종 (일반형·절개형·직선형)", model: "모델 EVA HIGH VOLTAGE INSULATING BLANKET 시리즈", category: "한전 보수용 자재 · YOTSUGI", price: null, url: "product-detail-sunsco-528.html" },
  { id: "product-detail-sunsco-529", name: "간접활선용 시트클립 (곡구A, 곡구B, 직구핀)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-529.html" },
  { id: "product-detail-sunsco-53", name: "오토스 보안면 F71A-XS | 안전모 결합형 보안면", model: "안전장구", category: "안전장구 · 안전장구", price: 24200, url: "product-detail-sunsco-53.html" },
  { id: "product-detail-sunsco-530", name: "부싱단자커버 (내염애자용)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-530.html" },
  { id: "product-detail-sunsco-533", name: "구조용삼각대(자동)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-533.html" },
  { id: "product-detail-sunsco-534", name: "구조용삼각대(수동)", model: "안전장구", category: "안전장구 · 안전장구", price: null, url: "product-detail-sunsco-534.html" },
  { id: "product-detail-sunsco-535", name: "위험표지판 (감전) 50개 | 주문 제작, 10일 소요", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 1017500, url: "product-detail-sunsco-535.html" },
  { id: "product-detail-sunsco-54", name: "클램프핀 직구 / 곡구", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 18150, url: "product-detail-sunsco-54.html" },
  { id: "product-detail-sunsco-55", name: "고무소매 (미제)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 550000, url: "product-detail-sunsco-55.html" },
  { id: "product-detail-sunsco-59", name: "Class 00 절연고무장갑 (500V)", model: "모델 CNOVAX-00", category: "간접활선공구 · NOVAX", price: 41800, url: "product-detail-sunsco-59.html" },
  { id: "product-detail-sunsco-60", name: "절연장갑 보호용 가죽장갑 (Salisbury 도메스틱 고트스킨)", model: "모델 LPG3S", category: "간접활선공구 · Salisbury", price: 37400, url: "product-detail-sunsco-60.html" },
  { id: "product-detail-sunsco-666", name: "칡넝쿨방지캡 대형 1박스 (3EA) | 덩굴 식물 차단 보호캡", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 148500, url: "product-detail-sunsco-666.html" },
  { id: "product-detail-sunsco-667", name: "감전방지 충전식 고지가위", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 1210000, url: "product-detail-sunsco-667.html" },
  { id: "product-detail-sunsco-7", name: "클램프메타 376FC | AC/DC 클램프 전류계", model: "모델 376FC", category: "계측기 · FLUKE", price: 638000, url: "product-detail-sunsco-7.html" },
  { id: "product-detail-sunsco-73", name: "수동식압축기 (Y-35)", model: "유압공구", category: "유압공구 · 유압공구", price: 616000, url: "product-detail-sunsco-73.html" },
  { id: "product-detail-sunsco-74", name: "유압임팩 (스탠리)", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-74.html" },
  { id: "product-detail-sunsco-75", name: "전동유압펌프 (다이아)", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-75.html" },
  { id: "product-detail-sunsco-76", name: "지중 케이블절단기 절단기헤드 P85YC (이즈미)", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-76.html" },
  { id: "product-detail-sunsco-77", name: "절단기 헤드 2 [국산 / 일체]", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-77.html" },
  { id: "product-detail-sunsco-78", name: "유압 압축기헤드 DL-13H (대림) (국산, 일제)", model: "유압공구", category: "유압공구 · 유압공구", price: null, url: "product-detail-sunsco-78.html" },
  { id: "product-detail-sunsco-79", name: "EK425CFM (Mini 충전식 유압 압착기)", model: "유압공구", category: "유압공구 · 유압공구", price: 2145000, url: "product-detail-sunsco-79.html" },
  { id: "product-detail-sunsco-796", name: "강관전주용 전주도색판 소형 (6M) 1박스 (50EA)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: 3630000, url: "product-detail-sunsco-796.html" },
  { id: "product-detail-sunsco-80", name: "EK12042CFM (압착력 최대 13톤의 충전식 유압 압착기)", model: "유압공구", category: "유압공구 · 유압공구", price: 3300000, url: "product-detail-sunsco-80.html" },
  { id: "product-detail-sunsco-81", name: "울트라 절단기 (85MM) ES85CFM", model: "유압공구", category: "유압공구 · 유압공구", price: 3355000, url: "product-detail-sunsco-81.html" },
  { id: "product-detail-sunsco-86", name: "COS 조작봉 YSC-300-2 | 전기 작업용 절연 조작봉", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 165000, url: "product-detail-sunsco-86.html" },
  { id: "product-detail-sunsco-87", name: "미니 절단기 (32mm) ES32CFM", model: "유압공구", category: "유압공구 · 유압공구", price: 1870000, url: "product-detail-sunsco-87.html" },
  { id: "product-detail-sunsco-88", name: "하이엔드 디지털 고압절연저항계 KEW 3127", model: "모델 KEW 3127", category: "계측기 · KYORITSU", price: 3190000, url: "product-detail-sunsco-88.html" },
  { id: "product-detail-sunsco-89", name: "다기능계측기 MET-500 | 전기 설비 종합 측정기", model: "모델 MET-500", category: "계측기 · 계측기", price: 385000, url: "product-detail-sunsco-89.html" },
  { id: "product-detail-sunsco-9001", name: "PV 절연접지 테스터 KEW 6024PV", model: "모델 KEW 6024PV", category: "계측기 · KYORITSU", price: 1171500, url: "product-detail-sunsco-9001.html" },
  { id: "product-detail-sunsco-9003", name: "저압 검전기 HTE-610W (하세가와)", model: "모델 HTE-610W", category: "계측기 · HASEGAWA", price: null, url: "product-detail-sunsco-9003.html" },
  { id: "product-detail-sunsco-9004", name: "주상안전대 YS108 | 죔줄·보조죔줄 (유신기업사)", model: "안전장구", category: "안전장구 · 안전장구", price: 159500, url: "product-detail-sunsco-9004.html" },
  { id: "product-detail-sunsco-9005", name: "주상안전대 YS88 | 죔줄·보조죔줄 (유신기업사)", model: "안전장구", category: "안전장구 · 안전장구", price: 235400, url: "product-detail-sunsco-9005.html" },
  { id: "product-detail-sunsco-9006", name: "주상안전대 YS88-1 | 인조피혁패드 (유신기업사)", model: "안전장구", category: "안전장구 · 안전장구", price: 231000, url: "product-detail-sunsco-9006.html" },
  { id: "product-detail-sunsco-9007", name: "활선 경보기 YS212 | AC 23kV (유신기업사)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-9007.html" },
  { id: "product-detail-sunsco-9008", name: "배전용 접지용구 YS303 | AC 23kV (유신기업사)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-9008.html" },
  { id: "product-detail-sunsco-9009", name: "절연 검측봉 YS307 | AC 23kV~345kV (유신기업사)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-9009.html" },
  { id: "product-detail-sunsco-9010", name: "지중기기 조작봉 YS311 | AC 20kV, 1.5m (유신기업사)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-9010.html" },
  { id: "product-detail-sunsco-9011", name: "지중기기 조작봉 YS312 | AC 30kV, 2.2m (유신기업사)", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: null, url: "product-detail-sunsco-9011.html" },
  { id: "product-detail-sunsco-9012", name: "절연 방호관(절연도체덮개) YSN205 | 23kV급, 단종 (유신기업사)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-9012.html" },
  { id: "product-detail-sunsco-9013", name: "절연 방호관(절연도체덮개) YSN305 | 23kV (유신기업사)", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-9013.html" },
  { id: "product-detail-sunsco-91", name: "절연저항계 IR4051-10", model: "모델 IR4051-10", category: "계측기 · HIOKI", price: 242000, url: "product-detail-sunsco-91.html" },
  { id: "product-detail-sunsco-92", name: "디지털다기능계측기 CEM-2400 [절연, 접지측정외] (청파)", model: "모델 DT-2400", category: "계측기 · CEM", price: 1155000, url: "product-detail-sunsco-92.html" },
  { id: "product-detail-sunsco-93", name: "저압검전기 TK-5060 | 저압 전압 검전기", model: "모델 TK-5060", category: "계측기 · TK (태광전자정밀)", price: 22000, url: "product-detail-sunsco-93.html" },
  { id: "product-detail-sunsco-94", name: "다전압검전기 YSD-210 | 고압 저압 겸용 전압 검전기", model: "모델 YSD-210", category: "계측기 · 유신기업사", price: 324500, url: "product-detail-sunsco-94.html" },
  { id: "product-detail-sunsco-95", name: "그리프 올 크램프스틱 1.5m YS 311", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 649000, url: "product-detail-sunsco-95.html" },
  { id: "product-detail-sunsco-96", name: "그리프 올 크램프스틱 2.2m YS 312", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 649000, url: "product-detail-sunsco-96.html" },
  { id: "product-detail-sunsco-97", name: "COS 덮개", model: "활선/절연", category: "간접활선공구 · 활선/절연", price: 209000, url: "product-detail-sunsco-97.html" },
  { id: "product-detail-sunsco-99", name: "절연저항계 IR4053-10 (PV Ω 기능)", model: "모델 IR4053-10", category: "계측기 · HIOKI", price: 474100, url: "product-detail-sunsco-99.html" },
  { id: "product-detail-sunsco-lineposts", name: "라인포스트애자커버", model: "한전 보수용 자재", category: "한전 보수용 자재 · 한전 보수용 자재", price: null, url: "product-detail-sunsco-lineposts.html" },
  { id: "product-detail-tie", name: "내후성 케이블타이 (옥외용)", model: "HT-CT100", category: " · HellermannTyton", price: 38000, url: "product-detail-tie.html" }
];
